services:
  browser:
    build:
      context: .
      network: host
      args:
        HTTP_PROXY: "http://127.0.0.1:8118"
        HTTPS_PROXY: "http://127.0.0.1:8118"
    container_name: hummingbot-log-browser
    ports:
      - "8501:8501"
    volumes:
      - ${SQLITE_DB_DIR:-/home/ubuntu/v2hum/hummingbot_v2/data}:/data
    environment:
      - SQLITE_DB_DIR=/data
    restart: unless-stopped

networks:
  default:
    name: hummingbot-network
